linters:
  disable-all: true
  enable:
    - gofumpt
    - govet
    - gci
    - staticcheck
    - paralleltest

issues:
  fix: true

linters-settings:
  gci:
    sections:
      - standard
      - prefix(github.com/sagernet/)
      - default
  staticcheck:
    go: '1.19'
