site_name: sing-box
site_author: nekohasekai
repo_url: https://github.com/SagerNet/sing-box
repo_name: SagerNet/sing-box
copyright: Copyright &copy; 2021 nekohasekai
edit_uri: ""
theme:
  name: material
  icon:
    logo: material/tools
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - header.autohide
nav:
  - Getting Started: index.md
  - Configuration:
      - configuration/index.md
      - Log: configuration/log.md
      - DNS:
          - configuration/dns/index.md
          - DNS Server: configuration/dns/server.md
          - DNS Rule: configuration/dns/rule.md
      - Inbound:
          - configuration/inbound/index.md
          - Direct: configuration/inbound/direct.md
          - Mixed: configuration/inbound/mixed.md
          - Socks: configuration/inbound/socks.md
          - HTTP: configuration/inbound/http.md
          - Shadowsocks: configuration/inbound/shadowsocks.md
      - Outbound:
          - configuration/outbound/index.md
          - Direct: configuration/outbound/direct.md
          - Block: configuration/outbound/block.md
          - Socks: configuration/outbound/socks.md
          - HTTP: configuration/outbound/http.md
          - Shadowsocks: configuration/outbound/shadowsocks.md
      - Route:
          - configuration/route/index.md
          - GeoIP: configuration/route/geoip.md
          - Geosite: configuration/route/geosite.md
          - Route Rule: configuration/route/rule.md
  - Examples:
      - examples/index.md
      - Shadowsocks Server: examples/ss-server.md
      - Shadowsocks Client: examples/ss-client.md
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SagerNet/sing-box
  generator: false
